version: '3.8'

services:
  db:
    image: mysql:8.0.39
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backDocker
      dockerfile: dev.Dockerfile
    container_name: docker-backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE: ${DATABASE}
      DB_HOST: ${DB_HOST}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-contracts
    volumes:
      - ./frontDocker/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
